email: roberto.calandra@berkeley.edu
author: Roberto Calandra, Erin Grant, Joaquin Vanschoren, Jane Wang
baseurl: ""

theme: jekyll-theme-cayman

# Google services
google_analytics: UA-99852557-1
google_verification:

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  auto_ids:       true
  
plugins_dir:
  - jekyll-seo-tag
  - jekyll-sitemap
